server:  
  port: 8080
  session-timeout: 30  
  tomcat.max-threads: 0  
  tomcat.uri-encoding: UTF-8  
  
spring:  
  datasource:  
    url : jdbc:mysql://localhost:3306/mysql?useSSL=false&serverTimezone=Asia/Taipei
    username : root  
    password : password  
    driverClassName : com.mysql.cj.jdbc.Driver
  jpa:  
    database : mysql  
    show-sql : true
	format_sql : true
  hibernate:  
      ddl-auto : update  
      dialect : org.hibernate.dialect.MySQL5Dialect  
